# Generated by Django 5.1.1 on 2024-09-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
