# Generated by Django 5.1.1 on 2024-10-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0003_contactrequest_approved_at_contactrequest_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follow_from', 'follow_to')},
        ),
    ]
