# Generated by Django 5.1.1 on 2024-10-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificationservice', '0002_customdevice_delete_fcmtoken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdevice',
            name='token',
        ),
    ]
